apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namePrefix: staging-

namespace: staging-chat-moderation

configMapGenerator:
- behavior: merge
  files:
  - config.ini=config.staging
  name: messaging-config
images:
- name: messaging-app
  newName: shivamkurtarkar/messaging-app
  newTag: 5309c723bf49d4d07cc68eebd8903ef81cc48cdd
