apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namePrefix: staging-

namespace: staging-chat-moderation

configMapGenerator:
  - name: messaging-config
    behavior: merge
    files:
      - config.ini
