apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-moderation-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: deployment/argoproj/base/apps/
    repoURL: git@github.com:shivkurtarkar/chat-moderation.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
