apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: chat-moderation-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destination:
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
  sourceRepos:
    - "*"
