apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml

patches:
  - path: redis_patch.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-redis

patchesStrategicMerge:
  - repo-server.yaml
  - server.yaml
namespace: argocd
