apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-classification-app
spec:
  selector:
    matchLabels:
      app: text-classification-app
  template:
    metadata:
      labels:
        app: text-classification-app
    spec:
      containers:
        - name: text-classification-app
          image: text-classification
          imagePullPolicy: Always
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://172.18.0.2:31989/"
              # value: "mlflow-tracking-service:5000/"
            - name: MLFLOW_S3_ENDPOINT_URL
              # value: "minio:9000/"
              value: "http://172.18.0.2:30608/"
            - name: AWS_ACCESS_KEY_ID
              value: "admin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "password"
            - name: MLFLOW_S3_IGNORE_TLS
              value: "true"
            - name: EXPERIMENT
              valueFrom:
                secretKeyRef:
                  name: model_deployment_info
                  key: EXPERIMENT
            - name: RUN_ID
              valueFrom:
                secretKeyRef:
                  name: model_deployment_info
                  key: RUN_ID
          resources: {}
          #  limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 9696
      imagePullSecrets:
        - name: regcred
