apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-classification-app
spec:
  selector:
    matchLabels:
      app: text-classification-app
  template:
    metadata:
      labels:
        app: text-classification-app
    spec:
      containers:
        - name: text-classification-app
          image: text-classification
          imagePullPolicy: Always
          env:
            - name: EXPERIMENT
              valueFrom:
                secretKeyRef:
                  name: model-deployment-info
                  key: EXPERIMENT
            - name: RUN_ID
              valueFrom:
                secretKeyRef:
                  name: model-deployment-info
                  key: RUN_ID
          resources: {}
          #  limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 9696
      imagePullSecrets:
        - name: regcred
