apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

images:
  - name: text-classification
    newName: shivamkurtarkar/text-classification
    newTag: v2

secretGenerator:
  - name: model-deployment-info
    envs:
      - model-deployment-info.env
