[tool.pylint.messages_control]

max-line-length = 88

disable = [
  "missing-docstring",
  "unused-argument",
  "no-value-for-parameter",
  "no-member",
  "no-else-return",
  "line-too-long",
  "fixme",
  "protected-access",
  "too-few-public-methods",
  "invalid-name"
]

[tool.black]
line-length = 80
target-version = ['py37']
skip-string-normalization = true


[tool.isort]
multi_line_output = 3
length_sort = true
