apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

base:
  - ../../helm_base

namespace: messaging-app-dev

resources:
  - namespace.yaml

images:
  - name:
    newName:
    newTag:

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: deployment
    path: patch/deployment_patch.yaml
