apiVersion: v1
data:
  artifactRepository: |
    s3:
      bucket: argobucket
      endpoint: 172.18.0.2:30608
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
      useSDKCreds: true
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
