apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging-app
spec:
  destination:
    name: ""
    namespace: chat-moderation
    server: "https://kubernetes.default.svc"
  source:
    path: deployment/frontend/manifest/
    repoURL: "git@github.com:shivkurtarkar/chat-moderation.git"
    targetRevision: HEAD
  project: default
