apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namePrefix: staging-

namespace: staging-chat-moderation
images:
- name: messaging-app
  newName: shivamkurtarkar/messaging-app
  newTag: 867701d0dc47bce86b08c2c7a644ed5f4e78d31b
- name: shivamkurtarkar/text-classification
  newName: shivamkurtarkar/text-classification
  newTag: stag-6301abbb89bc5edb968712bef469406afe6f07f5
