apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namePrefix: staging-

namespace: staging-chat-moderation
images:
  - name: shivamkurtarkar/text-classification
    newName: shivamkurtarkar/text-classification
    newTag: stag-6301abbb89bc5edb968712bef469406afe6f07f5

secretGenerator:
  - name: model-deployment-info
    behavior: merge
    envs:
      - model-deployment-info.env
