apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namePrefix: staging-

namespace: staging-chat-moderation
images:
- name: shivamkurtarkar/text-classification
  newName: shivamkurtarkar/text-classification
  newTag: stag-05b16baf6197842c748ae47912d3d6363b2f0088

secretGenerator:
- behavior: merge
  envs:
  - model-deployment-info.env
  name: model-deployment-info
