apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namePrefix: production-

namespace: production-chat-moderation

configMapGenerator:
  - name: messaging-config
    behavior: merge
    files:
      - config.ini=config.prod
