apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namePrefix: production-

namespace: production-chat-moderation

configMapGenerator:
- behavior: merge
  files:
  - config.ini=config.prod
  name: messaging-config
images:
- name: shivamkurtarkar/messaging-app
  newName: shivamkurtarkar/messaging-app
  newTag: prod-aefc364bc0e0892ef346279154b0bdce5cebbb51

patches:
- patch: "- op: replace\n  path: \"/spec/rules/0/host\"                \n  value:
    \"prod.app.127.0.0.1.nip.io\""
  target:
    kind: Ingress
    name: messaging-app-ingress
