apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ns.yaml
namePrefix: staging-

patches:
  - patch: |-
      - op: replace
        path: "/spec/source/path"
        value: "deployment/argoproj/overlays/staging/apps"
    target:
      kind: Application
      name: chat-moderation-root
