apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-tracking-server
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: mlflow
    server: "https://kubernetes.default.svc"
  source:
    path: deployment/mlflow_setup/manifest/overlays/production/
    repoURL: "git@github.com:shivkurtarkar/chat-moderation.git"
    targetRevision: master
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
