apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namePrefix: production-

namespace: production-chat-moderation

secretGenerator:
  - name: model-deployment-info
    behavior: merge
    envs:
      - model-deployment-info.env
