apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../workflows
  - ingress.yaml
  # - regcred.yaml

patchesStrategicMerge:
  - patch/workflow-controller-configmap.yaml
