apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml
- messaging-config-map.yaml
images:
- name: messaging-app
  newName: shivamkurtarkar/messaging-app
  newTag: 22eba1d53b4dc5ddb7b7dad2100d43fb882de316
