apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  selector:
    matchLabels:
      app:  adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer:4.6.3
        ports:
          - containerPort: 8080
        env:
          - name: ADMINER_DESIGN
            value: pass
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  labels:
    app: adminer
spec:
  selector:
    app: adminer
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
