apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: suspend-templates
spec:
  templates:
    - name: approve
      suspend: {}
    - name: delay
      description: |-
        Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
      inputs:
        parameters:
          - name: duration
      suspend:
        duration: "{{inputs.parameters.duration}}"
