apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namePrefix: standalone-

namespace: standalone-chat-moderation
images:
  - name: shivamkurtarkar/text-classification
    newName: shivamkurtarkar/standalone-text-classification
    newTag: abf67de345659c9431fe95481040cb7a60a94bca

secretGenerator:
  - name: model-deployment-info
    behavior: merge
    envs:
      - model-deployment-info.env

patchesStrategicMerge:
  - patch/deployment-env.yaml
