apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging-app
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-text-classification
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
