apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namePrefix: standalone-

namespace: standalone-chat-moderation

configMapGenerator:
  - name: messaging-config
    behavior: merge
    files:
      - config.ini=config.prod

images:
  - name: shivamkurtarkar/messaging-app
    newName: shivamkurtarkar/messaging-app
    newTag: prod-b2719a28c6f163c3fda9ea06fcc78e8e7cffe7a6

patches:
  - patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: "standalone.app.127.0.0.1.nip.io"
    target:
      kind: Ingress
      name: messaging-app-ingress
