apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml
# - messaging-config-map.yaml
configMapGenerator:
  - name: messaging-config
    behavior: create
    files:
      - config.ini=config.ini

images:
  - name: messaging-app
    newName: shivamkurtarkar/messaging-app
    newTag: c171364ea349cabb8f839517642ebae2ad3e460b
