apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.3.9/install.yaml
  - namespace.yaml
  - wf-templates
namespace: argo
